-- Sonar — accounts schema + auth columns + least-privilege grants.
--
-- Apply ONCE per cluster as `admin`, AFTER 000_app_role.sql. Run with the
-- migration runner (infra/sql/run.mjs) — NOT as a single batch: Aurora DSQL
-- allows only ONE DDL statement per transaction and forbids mixing DDL with
-- DML, so each statement below must execute on its own.
--
-- DSQL notes baked into this file:
--   * No FOREIGN KEY support — referential integrity is enforced in app code.
--   * ALTER TABLE ADD COLUMN takes a BARE column (no inline DEFAULT/UNIQUE);
--     uniqueness is added separately via CREATE UNIQUE INDEX ASYNC.
--   * UUIDs are generated by the app (crypto.randomUUID), per DSQL guidance to
--     use application-generated ids for even key distribution.

-- 1. Base table for FRESH clusters (no-op if it already exists). Anonymous,
--    claimed, and bot users are ALL rows here — the single canonical identity.
--    `handle` is an internal unique slug (= the id for anon rows); `email` /
--    `google_sub` are null until the account is claimed.
CREATE TABLE IF NOT EXISTS accounts (
  id            uuid PRIMARY KEY,
  handle        text NOT NULL,
  display_name  text NOT NULL,
  avatar_url    text,
  is_bot        boolean NOT NULL DEFAULT false,
  email         text,
  google_sub    text,
  auth_method   text,
  claimed_at    timestamptz,
  last_login_at timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- 2. Upgrade an EXISTING accounts table that predates auth (no-op on a table
--    freshly created by step 1). Bare columns only — DSQL disallows inline
--    constraints/defaults on ADD COLUMN.
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS google_sub text;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS auth_method text;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS claimed_at timestamptz;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS last_login_at timestamptz;

-- 3. Uniqueness — the security boundary. A unique index on email/google_sub is
--    what makes "one account per identity" atomic under DSQL's optimistic
--    concurrency, so two concurrent claims of the same email can't both win
--    (the loser gets a unique-violation we handle in app code). NULLs are
--    DISTINCT by default, so unclaimed anon rows (null email/google_sub) don't
--    collide. ASYNC = non-blocking build; on a fresh/empty table it's instant.
CREATE UNIQUE INDEX ASYNC IF NOT EXISTS accounts_handle_uniq      ON accounts (handle);
CREATE UNIQUE INDEX ASYNC IF NOT EXISTS accounts_email_uniq       ON accounts (email);
CREATE UNIQUE INDEX ASYNC IF NOT EXISTS accounts_google_sub_uniq  ON accounts (google_sub);

-- 4. Least-privilege grants for the app role (created in 000_app_role.sql). The
--    web server can read accounts, create anonymous rows, and claim/update them
--    — and nothing else. No DELETE, no DDL, no access to other tables.
--    NOTE: we do NOT `GRANT USAGE ON SCHEMA public` — DSQL treats `public` as a
--    managed system entity and rejects it ("feature not supported on system
--    entity"); USAGE on public is already available to roles by default, so the
--    table grant alone is sufficient.
GRANT SELECT, INSERT, UPDATE ON accounts TO sonar_app;
